# Site settings
title: Gabriel Oliva
header-img: img/home-bg.jpg
email: gfpoliva@gmail.com
description: "Personal blog"
baseurl:
url: "http://gabrieloliva.github.io"
twitter_username: gabrieloliva_
github_username:  gabrieloliva

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate_path: "page:num"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
